-- <auto-generated>
--   This code was generated by a tool.
--   Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
-- </auto-generated>
-- Tpl: SqlServerCreateTable-1.0.tt
-- Src: MailServer.tbl
/*
 * TABLE: [Commons].[MailServer]
 *
 * */

-- USE <database-name>
-- GO

-- DROP TABLE [Commons].[MailServer]
-- GO

CREATE TABLE [Commons].[MailServer]
(
      [Id] VARCHAR(64) NOT NULL
    , [Name] NVARCHAR(128) NOT NULL
    , [From] NVARCHAR(256) NOT NULL
    , [FromName] NVARCHAR(256) NOT NULL
    , [Port] INT NOT NULL
    , [RequiresSsl] TINYINT NOT NULL
    , [UserName] NVARCHAR(2048) NOT NULL
    , [Password] NVARCHAR(2048) NOT NULL
    , CONSTRAINT [PK_MailServer] PRIMARY KEY NONCLUSTERED ([Id])
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_MailServer_1] ON [Commons].[MailServer]
(
      [Name]
)
GO
