-- <auto-generated>
--   This code was generated by a tool.
--   Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
-- </auto-generated>
-- Tpl: SqlServerCreateTable-1.0.tt
-- Src: Audit.tbl
/*
 * TABLE: [Auditing].[Audit]
 *
 * */

-- USE <database-name>
-- GO

-- DROP TABLE [Auditing].[Audit]
-- GO

CREATE TABLE [Auditing].[Audit]
(
      [Id] INT NOT NULL
    , [PrevId] INT NULL
    , [NextId] INT NULL
    , [TenantId] INT NOT NULL
    , [Kind] VARCHAR(8) NOT NULL
    , [CreationTime] DATETIME2 NOT NULL
    , [IncidentId] INT NULL
    , [UserId] NVARCHAR(128) NOT NULL
    , [UserName] NVARCHAR(300) NOT NULL
    , [UserAuthority] NVARCHAR(128) NULL
    , [UserDisplayName] NVARCHAR(300) NULL
    , [SourceId] VARCHAR(512) NOT NULL
    , [SourceCaption] NVARCHAR(200) NOT NULL
    , [SourceDisplay] NVARCHAR(768) NULL
    , [SourceTypeName] VARCHAR(1024) NOT NULL
    , [Data] VARBINARY(MAX) NOT NULL
    , CONSTRAINT [PK_Audit] PRIMARY KEY NONCLUSTERED ([Id])
)
GO

CREATE NONCLUSTERED INDEX [IX_Audit_1] ON [Auditing].[Audit]
(
      [UserId]
    , [TenantId]
)
GO

CREATE NONCLUSTERED INDEX [IX_Audit_2] ON [Auditing].[Audit]
(
      [SourceId]
    , [SourceTypeName]
    , [TenantId]
)
GO

CREATE NONCLUSTERED INDEX [IX_Audit_3] ON [Auditing].[Audit]
(
      [SourceTypeName]
    , [TenantId]
)
GO

CREATE NONCLUSTERED INDEX [IX_Audit_4] ON [Auditing].[Audit]
(
      [SourceDisplay]
    , [TenantId]
)
GO
