-- <auto-generated>
--   This code was generated by a tool.
--   Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
-- </auto-generated>
-- Tpl: SqlServerCreateTable-1.0.tt
-- Src: Tenant.tbl
/*
 * TABLE: [Host].[Tenant]
 *
 * */

-- USE <database-name>
-- GO

-- DROP TABLE [Host].[Tenant]
-- GO

CREATE TABLE [Host].[Tenant]
(
      [Id] INT NOT NULL
    , [Ring] INT NOT NULL
    , [Name] VARCHAR(128) NOT NULL
    , [DisplayName] NVARCHAR(128) NOT NULL
    , [Email] NVARCHAR(256) NOT NULL
    , [Culture] VARCHAR(10) NOT NULL
    , [MailServerId] VARCHAR(64) NULL
    , [MailFromAddress] NVARCHAR(256) NULL
    , [MailFromName] NVARCHAR(256) NULL
    , [ConnectionString] NTEXT NULL
    , [ProvisionState] VARCHAR(24) NOT NULL
    , [SubscriptionState] VARCHAR(16) NOT NULL
    , [SubscriptionStateComment] NTEXT NULL
    , [TrialDurationInDays] INT NULL
    , [TenantTrialStarted] DATETIME2 NULL
    , [TenantTrialEnd] DATETIME2 NULL
    , CONSTRAINT [PK_Tenant] PRIMARY KEY CLUSTERED ([Id])
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Tenant_Name] ON [Host].[Tenant]
(
      [Name]
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Tenant_DisplayName] ON [Host].[Tenant]
(
      [DisplayName]
)
GO
