-- <auto-generated>
--   This code was generated by a tool.
--   Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
-- </auto-generated>
-- Tpl: SqlServerCreateTable-1.0.tt
-- Src: AuditIncident.tbl
/*
 * TABLE: [Auditing].[AuditIncident]
 *
 * */

-- USE <database-name>
-- GO

-- DROP TABLE [Auditing].[AuditIncident]
-- GO

CREATE TABLE [Auditing].[AuditIncident]
(
      [Id] INT IDENTITY(-2147483647,1) NOT NULL
    , [Kind] VARCHAR(48) NOT NULL
    , [CreationTime] DATETIME2 NOT NULL
    , [AuditId] INT NULL
    , [UserId] NVARCHAR(128) NULL
    , [UserName] NVARCHAR(300) NULL
    , [UserAuthority] NVARCHAR(128) NULL
    , [UserDisplayName] NVARCHAR(300) NULL
    , [ResolutionUserId] NVARCHAR(128) NULL
    , [ResolutionUserName] NVARCHAR(300) NULL
    , [ResolutionUserAuthority] NVARCHAR(128) NULL
    , [ResolutionUserDisplayName] NVARCHAR(300) NULL
    , [ResolvedTime] DATETIME2 NULL
    , [ResolutionOpinion] NVARCHAR(4000) NULL
    , [Data] VARBINARY(MAX) NOT NULL
    , CONSTRAINT [PK_AuditIncident] PRIMARY KEY NONCLUSTERED ([Id])
)
GO

CREATE NONCLUSTERED INDEX [IX_AuditIncident_1] ON [Auditing].[AuditIncident]
(
      [ResolvedTime]
)
GO
